sonar.projectKey=Ucv-ate-si-lab-08
sonar.projectName=Ucv-ate-si-lab-08
sonar.projectVersion=1.0

# Rutas de código a analizar
sonar.sources=agente_ucv
sonar.tests=tests

# Configuraciones de lenguaje
sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

# Exclusiones para evitar analizar basura
sonar.exclusions=**/.venv/**,**/__pycache__/**